refactor(http): human legible error debug bodies
Manually implement Debug for `twilight_http::Error`, providing custom
implementations for some error types that contain HTTP body bytes so
they can be converted to strings.

Old debug message (reformatted for readability):

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error {
    source: None,
    kind: Response {
        body: [
            123, 34, 99, 111, 100, 101, 34, 58, 32, 53, 48, 48, 51, 53, 44, 32,
            34, 101, 114, 114, 111, 114, 115, 34, 58, 32, 123, 34, 111, 112,
            116, 105, 111, 110, 115, 34, 58, 32, 123, 34, 49, 34, 58, 32, 123,
            34, 95, 101, 114, 114, 111, 114, 115, 34, 58, 32, 91, 123, 34, 99,
            111, 100, 101, 34, 58, 32, 34, 65, 80, 80, 76, 73, 67, 65, 84, 73,
            79, 78, 95, 67, 79, 77, 77, 65, 78, 68, 95, 79, 80, 84, 73, 79, 78,
            83, 95, 78, 65, 77, 69, 95, 73, 78, 86, 65, 76, 73, 68, 34, 44, 32,
            34, 109, 101, 115, 115, 97, 103, 101, 34, 58, 32, 34, 79, 112, 116,
            105, 111, 110, 32, 110, 97, 109, 101, 32, 97, 32, 105, 115, 32, 97,
            108, 114, 101, 97, 100, 121, 32, 117, 115, 101, 100, 32, 105, 110,
            32, 116, 104, 101, 115, 101, 32, 111, 112, 116, 105, 111, 110, 115,
            34, 125, 93, 125, 125, 125, 44, 32, 34, 109, 101, 115, 115, 97, 103,
            101, 34, 58, 32, 34, 73, 110, 118, 97, 108, 105, 100, 32, 70, 111,
            114, 109, 32, 66, 111, 100, 121, 34, 125
        ],
        error: General(GeneralApiError {
            code: 50035,
            message: "Invalid Form Body"
        }),
        status: StatusCode(400)
    }
}', examples/http-get-message.rs:66:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

New debug message (reformatted string body for readability):

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error {
    source: None,
    kind: Response {
        body: "{
            \"code\": 50035,
            \"errors\": {
                \"options\": {
                    \"1\": {
                        \"_errors\": [{
                            \"code\": \"APPLICATION_COMMAND_OPTIONS_NAME_INVALID\",
                            \"message\": \"Option name a is already used in these options\"
                        }]
                    }
                }
            },
            \"message\": \"Invalid Form Body\"
        }",
        error: General(GeneralApiError {
            code: 50035,
            message: "Invalid Form Body"
        }),
        status: StatusCode(400)
    }
}', examples/http-get-message.rs:66:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```