http: parse api errors in responses (#179)
* http: parse api errors in responses

When an error occurs, instead of just giving the user a slightly nested
response around a client/server error enum, provide an error variant
containing the status code, body, and parsed API error.

The API error contains an error code (a number, like 10001, 10002, or
30001) parsed as an enum and the description of the error provided by
the API.

In total, the type schema of a response error looks like this now:

```
Error::Response {
  body: [ bytes... ],
  error: ApiError {
    code: ErrorCode,
    message: String,
  },
  status: StatusCode,
}
```

Closes #28.

Signed-off-by: Vivian Hellyer <vivian@hellyer.dev>

* make api_error module public

Signed-off-by: Vivian Hellyer <vivian@hellyer.dev>

* log unknown api error code variants

Signed-off-by: Vivian Hellyer <vivian@hellyer.dev>