fix(http): percent encode emoji in URIs (#685)
Going from 0.2 to 0.3 breaks the `CreateEmoji` request and likely other
requests relating to emojis.

It seems they are no longer being percent encoded. This results in:

```
Error: BuildingRequest { source: http::Error(InvalidUri(InvalidUriChar)) }
```

when running the code from the method's documentation.

The only change that may have caused this to happen is using `hyper`
instead of `reqwest`, so it's likely `reqwest` was automatically percent
encoding them.

To fix this, percent encode emojis when formatting them.

Approved-by: Cassandra McCarthy <cassie@7596ff.com>
Approved-by: Valdemar Erk <valdemar@erk.io>
Approved-by: Vivian Hellyer <vivian@hellyer.dev>
Merged-by: Vivian Hellyer <vivian@hellyer.dev>
Signed-off-by: Sam Kirby <sam.kirby94@hotmail.co.uk>